name: Autograde

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install server dependencies
      run: |
        cd server
        npm ci

    - name: Install client dependencies
      run: |
        cd client
        npm ci

    - name: Lint client
      run: |
        cd client
        npm run lint

    - name: Build client
      run: |
        cd client
        npm run build

    - name: Test server startup
      run: |
        cd server
        timeout 10s npm start || echo "Server started successfully (timeout expected)"
